### PR TITLE
Add more tests to make sure the package does not regress.

### PR DESCRIPTION
**Pull request by vgvassilev**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@mcbarton, @fsfod, we seem to have a similar problem to the one we fixed in compiler-research/CppInterOp#196. I see that some of the exports are dependent on the MSVC version and I was wondering if we can carry these exports somehow in the `CppInterOpConfig.cmake`. Alternatively, we could use a sledgehammer like `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` but I am not sure if that's a good idea. Any thoughts?

**Comment by vgvassilev** [comment]
@conda-forge-admin, please rerender

**Comment by mcbarton** [comment]
> @mcbarton, @fsfod, we seem to have a similar problem to the one we fixed in [compiler-research/CppInterOp#196](https://github.com/compiler-research/CppInterOp/pull/196). I see that some of the exports are dependent on the MSVC version and I was wondering if we can carry these exports somehow in the `CppInterOpConfig.cmake`. Alternatively, we could use a sledgehammer like `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` but I am not sure if that's a good idea. Any thoughts?

@vgvassilev The export symbols method is known to be brittle to the version of MSVC used https://github.com/compiler-research/CppInterOp/issues/188#issuecomment-1912483771 . @fstod discusses his opinion on WINDOWS_EXPORT_ALL_SYMBOLS in this message, suggestion he doesn't think it will work. He also suggests a longer term solution than these methods.

**Comment by vgvassilev** [comment]
> > @mcbarton, @fsfod, we seem to have a similar problem to the one we fixed in [compiler-research/CppInterOp#196](https://github.com/compiler-research/CppInterOp/pull/196). I see that some of the exports are dependent on the MSVC version and I was wondering if we can carry these exports somehow in the `CppInterOpConfig.cmake`. Alternatively, we could use a sledgehammer like `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` but I am not sure if that's a good idea. Any thoughts?
> 
> @vgvassilev The export symbols method is known to be brittle to the version of MSVC used [compiler-research/CppInterOp#188 (comment)](https://github.com/compiler-research/CppInterOp/issues/188#issuecomment-1912483771) . @fstod discusses his opinion on WINDOWS_EXPORT_ALL_SYMBOLS in this message, suggestion he doesn't think it will work. He also suggests a longer term solution than these methods.

Yes. Understood. I believe https://github.com/compiler-research/CppInterOp/pull/213 fixes my problem for now...

**Comment by vgvassilev** [comment]
@conda-forge-admin, please rerender

**Review by alexander-penev — APPROVED** [review]

**Pull request merged**
