### PR TITLE
Add arm back to recipe

### PR DESCRIPTION
**Pull request by mcbarton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mcbarton** [comment]
@vgvassilev In the last commit, the part of the recipe that is in this PR was removed. In the cppinterop package files on conda forge (https://anaconda.org/conda-forge/cppinterop/files) you can see that the arm builds got dropped, and don't have the latest patches.

**Comment by vgvassilev** [comment]
> @vgvassilev In the last commit, the part of the recipe that is in this PR was removed. In the cppinterop package files on conda forge (https://anaconda.org/conda-forge/cppinterop/files) you can see that the arm builds got dropped, and don't have the latest patches.

I just wanted to make sure that the linter does not remove it automatically. That'd mean we need to add these builds somewhere so that the renderer does not delete them. I do not remember deleting them explicitly, although they were failing at some point for me.

**Comment by vgvassilev** [comment]
@conda-forge-admin, please rerender

**Comment by vgvassilev** [comment]
So the linter removes the arm builds probably because we need to put them somewhere in the configuration.

**Comment by mcbarton** [comment]
I will do some investigating to determine what needs to be added so they don't get removed.

**Comment by mcbarton** [comment]
@conda-forge-admin, please rerender

**Comment by mcbarton** [comment]
@conda-forge-admin, please rerender

**Comment by mcbarton** [comment]
@vgvassilev modifying the conda-forge.yml file has fixed the issue with the renderer. The renderer moved the Linux arm builds to use Travis for the CI. I squashed the commits. Can you review?

After this has been reviewed as ok and merged, I will fix the issue in the cpp-argparse and xeus-cpp feedstocks, as the issue with the renderer removing the arm jobs will exist there too.

**Review by alexander-penev — APPROVED** [review]

**Pull request merged**
