### PR TITLE
Add a package for v1.2.0

### PR DESCRIPTION
**Pull request by vgvassilev**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by alexander-penev — APPROVED** [review]

**Comment by vgvassilev** [comment]
@mcbarton, I was wondering what would it take to enable the wasm and windows infrastructure? I think we might need some inspiration from https://github.com/conda-forge/xeus-cpp-feedstock?

**Comment by vgvassilev** [comment]
@conda-forge-admin, please rerender

**Comment by vgvassilev** [comment]
> @mcbarton, I was wondering what would it take to enable the wasm and windows infrastructure? I think we might need some inspiration from https://github.com/conda-forge/xeus-cpp-feedstock?

It looks like xeus-cpp does not have a version under https://github.com/emscripten-forge/recipes/tree/main/recipes yet.

**Comment by vgvassilev** [comment]
@conda-forge-admin, please rerender

**Comment by vgvassilev** [comment]
@conda-forge-admin, please rerender

**Comment by mcbarton** [comment]
@vgvassilev I will look at this in more detail later today, but the first things which stand out to me are. 

In the CI when building on Windows we do not build the shared library so this needs to be remove
https://github.com/vgvassilev/cppinterop-feedstock/blob/6b82e516e33adb92f7d8214c53f3245c1ed5b58a/recipe/bld.bat#L24


I don't understand why this is referencing a Linux folder
https://github.com/vgvassilev/cppinterop-feedstock/blob/6b82e516e33adb92f7d8214c53f3245c1ed5b58a/recipe/bld.bat#L7

CppInterOp also works for arm, so maybe have the name of the folders include the architecture name (also assuming this bash script is also used for osx, then the reference to linux folders should be different on osx). 
https://github.com/vgvassilev/cppinterop-feedstock/blob/6b82e516e33adb92f7d8214c53f3245c1ed5b58a/recipe/build.sh#L10

On a similar note, there is no arm machines mentionn the ci support folder, as far as I can tell.

**Comment by mcbarton** [comment]
@vgvassilev I can't see in https://github.com/conda-forge/xeus-cpp-feedstock where they are doing the wasm build. A wasm build cannot make use the llvmdev in Conda-forge as it stands as it forces on zstd (see https://github.com/conda-forge/llvmdev-feedstock/blob/fe9f6c862670e0837b7630d958bf3597e9011914/recipe/build.sh#L44 ). There is currently no build of zstd in https://repo.mamba.pm/emscripten-forge we could make use of for CppInterOp build. How easily do you think it would be to get this changed?

**Review by alexander-penev — APPROVED** [review]

**Comment by vgvassilev** [comment]
> @vgvassilev I can't see in https://github.com/conda-forge/xeus-cpp-feedstock where they are doing the wasm build.

@mcbarton, that seems to be still a PR: https://github.com/emscripten-forge/recipes/pull/737

> A wasm build cannot make use the llvmdev in Conda-forge as it stands as it forces on zstd (see https://github.com/conda-forge/llvmdev-feedstock/blob/fe9f6c862670e0837b7630d958bf3597e9011914/recipe/build.sh#L44 ). There is currently no build of zstd in https://repo.mamba.pm/emscripten-forge we could make use of for CppInterOp build. How easily do you think it would be to get this changed?

Doesn't emscripten-forge have its own package for LLVM? Can't we use it instead?

**Comment by mcbarton** [comment]
> > A wasm build cannot make use the llvmdev in Conda-forge as it stands as it forces on zstd (see https://github.com/conda-forge/llvmdev-feedstock/blob/fe9f6c862670e0837b7630d958bf3597e9011914/recipe/build.sh#L44 ). There is currently no build of zstd in https://repo.mamba.pm/emscripten-forge we could make use of for CppInterOp build. How easily do you think it would be to get this changed?
> 
> Doesn't emscripten-forge have its own package for LLVM? Can't we use it instead?

Yes emscripten-forge has its own llvm-dev here https://github.com/emscripten-forge/recipes/blob/main/recipes/recipes_emscripten/llvm/build.sh. Have you put in any PRs relevant to CppInterOp to llvm 17 since version 17.0.4 since that's the one its building? See https://github.com/emscripten-forge/recipes/blob/ddcb55bf747a57b409b7a805220178c8b750e9f5/recipes/recipes_emscripten/llvm/recipe.yaml#L2C1-L3C1

**Comment by vgvassilev** [comment]
> > > A wasm build cannot make use the llvmdev in Conda-forge as it stands as it forces on zstd (see https://github.com/conda-forge/llvmdev-feedstock/blob/fe9f6c862670e0837b7630d958bf3597e9011914/recipe/build.sh#L44 ). There is currently no build of zstd in https://repo.mamba.pm/emscripten-forge we could make use of for CppInterOp build. How easily do you think it would be to get this changed?
> > 
> > 
> > Doesn't emscripten-forge have its own package for LLVM? Can't we use it instead?
> 
> Yes emscripten-forge has its own llvm-dev here https://github.com/emscripten-forge/recipes/blob/main/recipes/recipes_emscripten/llvm/build.sh. Have you put in any PRs relevant to CppInterOp to llvm 17 since version 17.0.4 since that's the one its building? See https://github.com/emscripten-forge/recipes/blob/ddcb55bf747a57b409b7a805220178c8b750e9f5/recipes/recipes_emscripten/llvm/recipe.yaml#L2C1-L3C1

We have not - CppInterOp should be compatible with 17.0.4.

**Comment by mcbarton** [comment]
> > > > A wasm build cannot make use the llvmdev in Conda-forge as it stands as it forces on zstd (see https://github.com/conda-forge/llvmdev-feedstock/blob/fe9f6c862670e0837b7630d958bf3597e9011914/recipe/build.sh#L44 ). There is currently no build of zstd in https://repo.mamba.pm/emscripten-forge we could make use of for CppInterOp build. How easily do you think it would be to get this changed?
> > > 
> > > 
> > > Doesn't emscripten-forge have its own package for LLVM? Can't we use it instead?
> > 
> > 
> > Yes emscripten-forge has its own llvm-dev here https://github.com/emscripten-forge/recipes/blob/main/recipes/recipes_emscripten/llvm/build.sh. Have you put in any PRs relevant to CppInterOp to llvm 17 since version 17.0.4 since that's the one its building? See https://github.com/emscripten-forge/recipes/blob/ddcb55bf747a57b409b7a805220178c8b750e9f5/recipes/recipes_emscripten/llvm/recipe.yaml#L2C1-L3C1
> 
> We have not - CppInterOp should be compatible with 17.0.4.

If you know someone who can get it reviewed and approved, then I can make a start on a recipe for CppInterOp in emscripten-forge sometime in the next few days if you would like.

**Comment by vgvassilev** [comment]
> > > > > A wasm build cannot make use the llvmdev in Conda-forge as it stands as it forces on zstd (see https://github.com/conda-forge/llvmdev-feedstock/blob/fe9f6c862670e0837b7630d958bf3597e9011914/recipe/build.sh#L44 ). There is currently no build of zstd in https://repo.mamba.pm/emscripten-forge we could make use of for CppInterOp build. How easily do you think it would be to get this changed?
> > > > 
> > > > 
> > > > Doesn't emscripten-forge have its own package for LLVM? Can't we use it instead?
> > > 
> > > 
> > > Yes emscripten-forge has its own llvm-dev here https://github.com/emscripten-forge/recipes/blob/main/recipes/recipes_emscripten/llvm/build.sh. Have you put in any PRs relevant to CppInterOp to llvm 17 since version 17.0.4 since that's the one its building? See https://github.com/emscripten-forge/recipes/blob/ddcb55bf747a57b409b7a805220178c8b750e9f5/recipes/recipes_emscripten/llvm/recipe.yaml#L2C1-L3C1
> > 
> > 
> > We have not - CppInterOp should be compatible with 17.0.4.
> 
> If you know someone who can get it reviewed and approved, then I can make a start on a recipe for CppInterOp in emscripten-forge sometime in the next few days if you would like.

Yes, we do. Maybe we should try doing this to unblock compiler-research/xeus-cpp#14.

**Comment by mcbarton** [comment]
> > > > > > A wasm build cannot make use the llvmdev in Conda-forge as it stands as it forces on zstd (see https://github.com/conda-forge/llvmdev-feedstock/blob/fe9f6c862670e0837b7630d958bf3597e9011914/recipe/build.sh#L44 ). There is currently no build of zstd in https://repo.mamba.pm/emscripten-forge we could make use of for CppInterOp build. How easily do you think it would be to get this changed?
> > > > > 
> > > > > 
> > > > > Doesn't emscripten-forge have its own package for LLVM? Can't we use it instead?
> > > > 
> > > > 
> > > > Yes emscripten-forge has its own llvm-dev here https://github.com/emscripten-forge/recipes/blob/main/recipes/recipes_emscripten/llvm/build.sh. Have you put in any PRs relevant to CppInterOp to llvm 17 since version 17.0.4 since that's the one its building? See https://github.com/emscripten-forge/recipes/blob/ddcb55bf747a57b409b7a805220178c8b750e9f5/recipes/recipes_emscripten/llvm/recipe.yaml#L2C1-L3C1
> > > 
> > > 
> > > We have not - CppInterOp should be compatible with 17.0.4.
> > 
> > 
> > If you know someone who can get it reviewed and approved, then I can make a start on a recipe for CppInterOp in emscripten-forge sometime in the next few days if you would like.
> 
> Yes, we do. Maybe we should try doing this to unblock [compiler-research/xeus-cpp#14](https://github.com/compiler-research/xeus-cpp/pull/14).

Ok. Once I have a draft of a recipe ready for testing I will cc you in the PR, and we can take it from there.

**Pull request merged**
